### PR TITLE
[AllReduce] Enable FP8 conditions only if FP8 is supported

### PR DESCRIPTION
**Pull request by nileshnegi**
## Details

**Work item:**
https://github.com/ROCm/rccl-tests/issues/103

**What were the changes?**  
Wrap FP8-based conditions in AllReduce (introduced in https://github.com/ROCm/rccl-tests/commit/77ae744c181c02fade85b8b0536b5dba8928c461) to enable logic only if FP8 is supported.

**Why were the changes made?**  
Compilation errors on older ROCm which does not support FP8.

### CODE REVIEW

**Comment by ammallya** [comment]
Cannot import to ROCm/rocm-systems due to merge conflicts. Please reopen the PR on ROCm/rocm-systems.
